methods: [mha, mqa, gqa, mla]

# Shared
n_layer: 8
embd_dims: 512
block_size: 256
batch_size: 32
num_steps: 30000
lr: 3.0e-4

# MHA/MQA
n_head: 8

# GQA/MLA
n_qhead: 8
n_kvhead: 2

# MLA / DSA
latent_dims: 256
rope_dims: 64
top_k: 64
warmup_steps: 2000

# Inference
infer_batch: 64
max_new_tokens: 255
